services:
  - type: web
    name: travel-vista
    env: static
    repo: https://github.com/Harshit-jain-786/TravelIndia
    branch: main   # change if using master
    buildCommand: npm install && npm run build
    staticPublishPath: dist
